import type { Listing } from '@airbnb-clone/shared';

const imageBaseUrl = 'http://localhost:3000/listing';

export const listingSeedData: Listing = {
  title: 'Romantic Jacuzzi 1BHK Candolim | Mirashya UG10',
  slug: 'romantic-jacuzzi-1bhk-candolim-mirashya-ug10',
  description:
    'A premium oceanfront stay with private pool, expansive deck, and sunset views.',
  propertyType: 'entire-home',
  maxGuests: 8,
  bedrooms: 4,
  bathrooms: 3.5,
  host: {
    name: 'Aarav Mehta',
    avatar: 'https://example.com/avatars/aarav-mehta.jpg',
    isSuperhost: true,
    responseRate: 99,
    responseTime: 'within an hour',
    joinedYear: 2018,
  },
  pricing: {
    currency: 'USD',
    basePrice: 420,
    cleaningFee: 85,
    serviceFee: 62,
    taxes: 48,
    weeklyDiscountPercentage: 10,
    monthlyDiscountPercentage: 18,
  },
  images: [
    {
      id: 'listing-01',
      url: `${imageBaseUrl}/listing-01.jpeg`,
      alt: 'Warm living room with a TV console, wooden furniture, and kitchen entryway',
      width: 1440,
      height: 960,
      order: 1,
      category: 'living-room',
      isHero: true,
    },
    {
      id: 'listing-02',
      url: `${imageBaseUrl}/listing-02.jpeg`,
      alt: 'Indoor spa lounge with rattan seating, feature wall, and jacuzzi area',
      width: 1440,
      height: 960,
      order: 2,
      category: 'interior',
      isHero: false,
    },
    {
      id: 'listing-03',
      url: `${imageBaseUrl}/listing-03.jpeg`,
      alt: 'Open living and kitchen area with a dining table, wood accents, and bright windows',
      width: 1440,
      height: 960,
      order: 3,
      category: 'living-room',
      isHero: false,
    },
    {
      id: 'listing-04',
      url: `${imageBaseUrl}/listing-04.jpeg`,
      alt: 'Compact sink and laundry nook with grey tile walls',
      width: 1440,
      height: 960,
      order: 4,
      category: 'bathroom',
      isHero: false,
    },
    {
      id: 'listing-05',
      url: `${imageBaseUrl}/listing-05.jpeg`,
      alt: 'Bright shared lounge with spa seating and a dining area',
      width: 1440,
      height: 960,
      order: 5,
      category: 'interior',
      isHero: false,
    },
    {
      id: 'listing-06',
      url: `${imageBaseUrl}/listing-06.jpeg`,
      alt: 'Rattan seating area with a textured grey feature wall',
      width: 1440,
      height: 960,
      order: 6,
      category: 'living-room',
      isHero: false,
    },
    {
      id: 'listing-07',
      url: `${imageBaseUrl}/listing-07.jpeg`,
      alt: 'Kitchen wall with sink, washer, and framed artwork',
      width: 1440,
      height: 960,
      order: 7,
      category: 'kitchen',
      isHero: false,
    },
    {
      id: 'listing-08',
      url: `${imageBaseUrl}/listing-08.jpeg`,
      alt: 'Spa corner with wood-clad tub steps and lounge chairs',
      width: 1440,
      height: 960,
      order: 8,
      category: 'outdoor',
      isHero: false,
    },
    {
      id: 'listing-09',
      url: `${imageBaseUrl}/listing-09.jpeg`,
      alt: 'High-ceiling indoor courtyard with a jacuzzi and lounge seating',
      width: 1440,
      height: 960,
      order: 9,
      category: 'interior',
      isHero: false,
    },
    {
      id: 'listing-10',
      url: `${imageBaseUrl}/listing-10.jpeg`,
      alt: 'Close-up of the spa lounge with textured wall lighting',
      width: 1440,
      height: 960,
      order: 10,
      category: 'outdoor',
      isHero: false,
    },
    {
      id: 'listing-11',
      url: `${imageBaseUrl}/listing-11.jpeg`,
      alt: 'Aerial view of the apartment courtyard and pool',
      width: 1440,
      height: 960,
      order: 11,
      category: 'exterior',
      isHero: false,
    },
    {
      id: 'listing-12',
      url: `${imageBaseUrl}/listing-12.jpeg`,
      alt: 'Pool deck view inside the apartment courtyard',
      width: 1440,
      height: 960,
      order: 12,
      category: 'exterior',
      isHero: false,
    },
    {
      id: 'listing-13',
      url: `${imageBaseUrl}/listing-13.jpeg`,
      alt: 'Courtyard pool with surrounding balconies and planted edges',
      width: 1440,
      height: 960,
      order: 13,
      category: 'exterior',
      isHero: false,
    },
    {
      id: 'listing-14',
      url: `${imageBaseUrl}/listing-14.jpeg`,
      alt: 'Drone shot of the building rooftop and nearby greenery',
      width: 1440,
      height: 960,
      order: 14,
      category: 'exterior',
      isHero: false,
    },
    {
      id: 'listing-15',
      url: `${imageBaseUrl}/listing-15.jpeg`,
      alt: 'Aerial corner view of the building and the street outside',
      width: 1440,
      height: 960,
      order: 15,
      category: 'exterior',
      isHero: false,
    },
    {
      id: 'listing-16',
      url: `${imageBaseUrl}/listing-16.jpeg`,
      alt: 'Building rooftop and surrounding neighborhood from above',
      width: 1440,
      height: 960,
      order: 16,
      category: 'exterior',
      isHero: false,
    },
    {
      id: 'listing-17',
      url: `${imageBaseUrl}/listing-17.jpeg`,
      alt: 'Wide aerial landscape shot with the sea in the distance',
      width: 1440,
      height: 960,
      order: 17,
      category: 'view',
      isHero: false,
    },
    {
      id: 'listing-18',
      url: `${imageBaseUrl}/listing-18.jpeg`,
      alt: 'Aerial view looking down on the building and the coastline',
      width: 1440,
      height: 960,
      order: 18,
      category: 'view',
      isHero: false,
    },
    {
      id: 'listing-19',
      url: `${imageBaseUrl}/listing-19.jpeg`,
      alt: 'Small gym with a cable machine and bench',
      width: 1440,
      height: 960,
      order: 19,
      category: 'workspace',
      isHero: false,
    },
    {
      id: 'listing-20',
      url: `${imageBaseUrl}/listing-20.jpeg`,
      alt: 'Fitness room with treadmill, elliptical, and dumbbell rack',
      width: 1440,
      height: 960,
      order: 20,
      category: 'workspace',
      isHero: false,
    },
    {
      id: 'listing-21',
      url: `${imageBaseUrl}/listing-21.jpeg`,
      alt: 'Gym area with multiple machines and a bench',
      width: 1440,
      height: 960,
      order: 21,
      category: 'workspace',
      isHero: false,
    },
    {
      id: 'listing-22',
      url: `${imageBaseUrl}/listing-22.jpeg`,
      alt: 'Solo workout room with cable machine and stability ball',
      width: 1440,
      height: 960,
      order: 22,
      category: 'workspace',
      isHero: false,
    },
    {
      id: 'listing-23',
      url: `${imageBaseUrl}/listing-23.jpeg`,
      alt: 'Gym floor with cardio machines and dumbbells',
      width: 1440,
      height: 960,
      order: 23,
      category: 'workspace',
      isHero: false,
    },
    {
      id: 'listing-24',
      url: `${imageBaseUrl}/listing-24.jpeg`,
      alt: 'Modern bathroom with rain shower, sink, and toilet',
      width: 1440,
      height: 960,
      order: 24,
      category: 'bathroom',
      isHero: false,
    },
    {
      id: 'listing-25',
      url: `${imageBaseUrl}/listing-25.jpeg`,
      alt: 'Single bedroom with a neatly made bed and bedside lighting',
      width: 1440,
      height: 960,
      order: 25,
      category: 'bedroom',
      isHero: false,
    },
    {
      id: 'listing-26',
      url: `${imageBaseUrl}/listing-26.jpeg`,
      alt: 'Bedroom with wardrobe, wall lamp, and air conditioning',
      width: 1440,
      height: 960,
      order: 26,
      category: 'bedroom',
      isHero: false,
    },
    {
      id: 'listing-27',
      url: `${imageBaseUrl}/listing-27.jpeg`,
      alt: 'Cozy bedroom with curtains, wardrobe, and doorway to the living area',
      width: 1440,
      height: 960,
      order: 27,
      category: 'bedroom',
      isHero: false,
    },
    {
      id: 'listing-28',
      url: `${imageBaseUrl}/listing-28.jpeg`,
      alt: 'Bedroom with a double bed, pendant lamp, and bathroom entry',
      width: 1440,
      height: 960,
      order: 28,
      category: 'bedroom',
      isHero: false,
    },
    {
      id: 'listing-29',
      url: `${imageBaseUrl}/listing-29.jpeg`,
      alt: 'Hallway view into the bedroom from the landing',
      width: 1440,
      height: 960,
      order: 29,
      category: 'bedroom',
      isHero: false,
    },
    {
      id: 'listing-30',
      url: `${imageBaseUrl}/listing-30.jpeg`,
      alt: 'Bright bedroom with window light and a curtain wall',
      width: 1440,
      height: 960,
      order: 30,
      category: 'bedroom',
      isHero: false,
    },
    {
      id: 'listing-31',
      url: `${imageBaseUrl}/listing-31.jpeg`,
      alt: 'Compact kitchen with cooktop, sink, and dining nook',
      width: 1440,
      height: 960,
      order: 31,
      category: 'kitchen',
      isHero: false,
    },
    {
      id: 'listing-32',
      url: `${imageBaseUrl}/listing-32.jpeg`,
      alt: 'Kitchen counter with fridge, cooktop, and warm wood cabinetry',
      width: 1440,
      height: 960,
      order: 32,
      category: 'kitchen',
      isHero: false,
    },
    {
      id: 'listing-33',
      url: `${imageBaseUrl}/listing-33.jpeg`,
      alt: 'Shared interior seating area with high ceilings and plants',
      width: 1440,
      height: 960,
      order: 33,
      category: 'interior',
      isHero: false,
    },
    {
      id: 'listing-34',
      url: `${imageBaseUrl}/listing-34.jpeg`,
      alt: 'Indoor spa courtyard with lounge chairs and stairs to the tub',
      width: 1440,
      height: 960,
      order: 34,
      category: 'interior',
      isHero: false,
    },
    {
      id: 'listing-35',
      url: `${imageBaseUrl}/listing-35.jpeg`,
      alt: 'Wide spa lounge view with the hot tub at one side',
      width: 1440,
      height: 960,
      order: 35,
      category: 'living-room',
      isHero: false,
    },
    {
      id: 'listing-36',
      url: `${imageBaseUrl}/listing-36.jpeg`,
      alt: 'Seating area centered on the lounge space and indoor courtyard',
      width: 1440,
      height: 960,
      order: 36,
      category: 'living-room',
      isHero: false,
    },
    {
      id: 'listing-37',
      url: `${imageBaseUrl}/listing-37.jpeg`,
      alt: 'Courtyard lounge seen from the spa deck with stair details',
      width: 1440,
      height: 960,
      order: 37,
      category: 'interior',
      isHero: false,
    },
    {
      id: 'listing-38',
      url: `${imageBaseUrl}/listing-38.jpeg`,
      alt: 'Close-up of the built-in jacuzzi and window wall',
      width: 1440,
      height: 960,
      order: 38,
      category: 'outdoor',
      isHero: false,
    },
    {
      id: 'listing-39',
      url: `${imageBaseUrl}/listing-39.jpeg`,
      alt: 'Lounge seating beside the jacuzzi with stone feature wall',
      width: 1440,
      height: 960,
      order: 39,
      category: 'outdoor',
      isHero: false,
    },
    {
      id: 'listing-40',
      url: `${imageBaseUrl}/listing-40.jpeg`,
      alt: 'Living room with mounted TV showing nature footage',
      width: 1440,
      height: 960,
      order: 40,
      category: 'living-room',
      isHero: false,
    },
    {
      id: 'listing-41',
      url: `${imageBaseUrl}/listing-41.jpeg`,
      alt: 'Living room with curtain-lined window and TV feature wall',
      width: 1440,
      height: 960,
      order: 41,
      category: 'living-room',
      isHero: false,
    },
    {
      id: 'listing-42',
      url: `${imageBaseUrl}/listing-42.jpeg`,
      alt: 'Orange sofa in the living room facing the kitchen and dining area',
      width: 1440,
      height: 960,
      order: 42,
      category: 'living-room',
      isHero: false,
    },
    {
      id: 'listing-43',
      url: `${imageBaseUrl}/listing-43.jpeg`,
      alt: 'Outdoor spa seating with the jacuzzi and textured wall',
      width: 1440,
      height: 960,
      order: 43,
      category: 'outdoor',
      isHero: false,
    },
  ],
  amenities: [
    {
      category: 'guest-favorite',
      items: [
        { id: 'wifi', title: 'Fast Wi-Fi', icon: 'wifi', available: true },
        { id: 'pool', title: 'Private Pool', icon: 'pool', available: true },
      ],
    },
    {
      category: 'kitchen',
      items: [
        {
          id: 'coffee-maker',
          title: 'Coffee Maker',
          icon: 'coffee',
          available: true,
        },
      ],
    },
  ],
  rooms: [
    {
      roomName: 'Master Bedroom',
      beds: [
        { type: 'king', count: 1 },
        { type: 'sofa-bed', count: 1 },
      ],
    },
    {
      roomName: 'Guest Bedroom',
      beds: [{ type: 'queen', count: 1 }],
    },
  ],
  reviewSummary: {
    averageRating: 4.93,
    totalReviews: 128,
  },
  reviews: [
    {
      reviewerName: 'Sophia',
      avatar: 'https://example.com/avatars/sophia.jpg',
      rating: 5,
      date: '2026-05-18T00:00:00.000Z',
      comment: 'Beautiful space, exactly as shown, and great communication.',
    },
  ],
  propertyHighlights: [
    {
      title: 'Panoramic Ocean View',
      description: 'Floor-to-ceiling windows across the main living area.',
    },
    {
      title: 'Private Outdoor Lounge',
      description: 'Large deck with shaded seating and dining setup.',
    },
  ],
  thingsToKnow: {
    houseRules: ['No smoking indoors', 'Quiet hours after 10 PM'],
    safety: ['Smoke alarm installed', 'First aid kit available'],
    cancellationPolicy: ['Free cancellation within 48 hours of booking'],
  },
  location: {
    city: 'Goa',
    country: 'India',
    latitude: 15.2993,
    longitude: 74.124,
  },
  metadata: {
    status: 'published',
    featured: true,
  },
  seo: {
    title: 'Romantic Jacuzzi 1BHK Candolim | Mirashya UG10',
    description:
      'Stay in a luxury oceanfront villa in Goa with a private infinity pool and modern amenities.',
    keywords: ['goa villa', 'oceanfront stay', 'private pool'],
  },
};
